import ROOT
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages
from scipy.optimize import curve_fit
import ROOT as root

###################################################################### DEFINITIONS #####################################################################################

ROOT.gROOT.SetBatch(True)
nObj = 0

class File:
    def __init__(self,infile):
        if (isinstance(infile,ROOT.TFile)):
            self.TFile = infile
        else:
            self.TFile = ROOT.TFile(infile)

    def get(self,name,**kwargs):
        # if (not self.TFile.GetListOfKeys().Contains(name)):
            # raise ValueError("File does not contain specified object")
        h = self.TFile.Get(name)
        if (isinstance(h,ROOT.TH2)):
            return Hist2D(h,**kwargs)
        elif (isinstance(h,ROOT.TH1)):
            return Hist1D(h,**kwargs)
        else:
            raise ValueError("Object is not a supported type")

    def getNames(self):
        return [i.GetName() for i in self.TFile.GetListOfKeys()]

    def plotPoints(self,name,rebin=1,scale=1,**kwargs):
        h = self.get(name,rebin=rebin,scale=scale)
        if (isinstance(h,Hist1D)):
            return h.plotPoints(**kwargs)
        else:
            raise ValueError("This is not a 1D histogram and cannot be plotted with this method")

    def plotBand(self,name,rebin=1,scale=1,**kwargs):
        h = self.get(name,rebin=rebin,scale=scale)
        if (isinstance(h,Hist1D)):
            return h.plotBand(**kwargs)
        else:
            raise ValueError("This is not a 1D histogram and cannot be plotted with this method")

    def plotBar(self,name,rebin=1,scale=1,**kwargs):
        h = self.get(name,rebin=rebin,scale=scale)
        if (isinstance(h,Hist1D)):
            return h.plotBar(**kwargs)
        else:
            raise ValueError("This is not a 1D histogram and cannot be plotted with this method")

    def plotHeatmap(self,name,rebinx=1,rebiny=1,**kwargs):
        h = self.get(name,rebinx=rebinx,rebiny=rebiny)
        if (isinstance(h,Hist2D)):
            return h.plotHeatmap(**kwargs)
        else:
            raise ValueError("This is not a 2D histogram and cannot be plotted with this method")

class Hist1D:
    def __init__(self,hist,rebin=1,scale=1):
        global nObj
        self.TH1 = hist.Clone(str(nObj))
        nObj = nObj + 1

        if (rebin != 1):
            self.TH1.Rebin(rebin)

        g = ROOT.TGraphAsymmErrors(self.TH1)
        self.x = np.array(g.GetX())
        self.y = np.array(g.GetY())*scale
        xerr = []
        yerr = []
        for i in range(g.GetN()):
            xerr.append(g.GetErrorX(i))
            yerr.append(g.GetErrorY(i))
        self.xerr = np.array(xerr)
        self.yerr = np.array(yerr)*scale

    def scale(self,factor):
        self.y *= factor
        self.yerr *= factor

    def rebin(self,factor):
        if (factor != 1):
            self.TH1.Rebin(factor)
            g = ROOT.TGraphAsymmErrors(self.TH1)
            self.x = np.array(g.GetX())
            self.y = np.array(g.GetY())
            xerr = []
            yerr = []
            for i in range(g.GetN()):
                xerr.append(g.GetErrorX(i))
                yerr.append(g.GetErrorY(i))
            self.xerr = np.array(xerr)
            self.yerr = np.array(yerr)

    def areaNorm(self,reference):
        factor = np.sum(reference.y)/np.sum(self.y)
        self.scale(factor)
        return factor

    def plotPoints(self,**kwargs):
        return plt.errorbar(self.x,self.y,yerr=self.yerr,**kwargs)

    def plotBand(self,alpha=0.25,**kwargs):
        line = plt.plot(self.x,self.y,**kwargs)[0]
        band = plt.fill_between(self.x,self.y-self.yerr,self.y+self.yerr,
                                color=line.get_color(),zorder=line.zorder,
                                alpha=alpha)
        return line, band

    def plotBar(self,shift=0,**kwargs):
        bar = plt.bar(self.x+shift, self.y, **kwargs)

        return bar

class Hist2D:
    def __init__(self,hist,rebinx=1,rebiny=1):
        global nObj
        self.TH2 = hist.Clone(str(nObj))
        nObj = nObj + 1

        if (rebinx != 1):
            self.TH2.RebinX(rebinx)
        if (rebiny != 1):
            self.TH2.RebinY(rebiny)

        NX = self.TH2.GetNbinsX()
        NY = self.TH2.GetNbinsY()

        xedge = []
        yedge = []
        z = []
        zerr = []

        for j in range(NX):
            xedge.append(self.TH2.GetXaxis().GetBinLowEdge(j+1))
        xedge.append(self.TH2.GetXaxis().GetBinUpEdge(NX))

        for i in range(NY):
            yedge.append(self.TH2.GetYaxis().GetBinLowEdge(i+1))
            zcol = []
            zerrcol = []
            for j in range(NX):
                zval = self.TH2.GetBinContent(j+1,i+1)
                zcol.append(zval)
                zerrcol.append(self.TH2.GetBinError(j+1,i+1))
            z.append(zcol)
            zerr.append(zerrcol)
        yedge.append(self.TH2.GetYaxis().GetBinUpEdge(NY))

        self.xedge = np.array(xedge)
        self.yedge = np.array(yedge)
        self.z = np.array(z)
        self.zerr = np.array(zerr)

    def scale(self,factor):
        self.z *= factor
        self.zerr *= factor

    def plotHeatmap(self,kill_zeros=True,**kwargs):
        z = self.z
        if (kill_zeros):
            z[z==0] = np.nan
        return plt.pcolormesh(self.xedge,self.yedge,self.z,**kwargs)

    def projectionX(self,**kwargs):
        return Hist1D(self.TH2.ProjectionX(),**kwargs)

    def projectionY(self,**kwargs):
        return Hist1D(self.TH2.ProjectionY(),**kwargs)

###################################################################### READ THE FILES #####################################################################################

file_pdf    = PdfPages("/work/halld2/home/boyu/src_analysis/filter/output/hist_vm_d.pdf")
file_data   = File("/work/halld2/home/boyu/src_analysis/filter/output/filteredhist_phi_d_recon_exc_data_2H_ver12.root")
file_sim    = File("/work/halld2/home/boyu/src_analysis/filter/output/filteredhist_phi_d_recon_exc_sim_2H_ver12_flat.root")
file_tagged = File("/work/halld2/home/boyu/src_analysis/filter/output/filteredhist_phi_d_thrown_exc_tagged_2H_ver12_flat.root")
file_gen    = File("/work/halld2/home/boyu/src_analysis/filter/output/filteredhist_phi_d_thrown_exc_gen_2H_ver12_flat.root")

###################################################################### CUTS RELATED #####################################################################################

# K+ kinematics
print("K+ kinematics")
fig = plt.figure(figsize=(16, 6), dpi=300)
gs = fig.add_gridspec(1, 2)
axs = gs.subplots()
hist_data = file_data.get('KinematicsCut/kp_kinematics_meas_KinematicsCut')
hist_sim = file_sim.get('KinematicsCut/kp_kinematics_meas_KinematicsCut')
hist_sim.scale(0.02)
plt.axes(axs[0])
hist_data.plotHeatmap()
plt.text(0.95, 0.95, "data", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
plt.axes(axs[1])
hist_sim.plotHeatmap()
plt.text(0.95, 0.95, "simulation", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
for i in range(2):
    plt.axes(axs[i])
    plt.plot([0,10], [2,2], '-', color='red')
    plt.plot([0.4,0.4], [0,20], '-', color='red')
    plt.xlim(0, 10)
    plt.ylim(0, 20)
    plt.yticks(np.arange(0, 21, 2))
    plt.xlabel(r"$p_{K^+}$ (GeV/c)")
    plt.ylabel(r"$\theta_{K^+}$ (deg)")
file_pdf.savefig()
plt.close()

# K- kinematics
print("K- kinematics")
fig = plt.figure(figsize=(16, 6), dpi=300)
gs = fig.add_gridspec(1, 2)
axs = gs.subplots()
hist_data = file_data.get('KinematicsCut/km_kinematics_meas_KinematicsCut')
hist_sim = file_sim.get('KinematicsCut/km_kinematics_meas_KinematicsCut')
hist_sim.scale(0.02)
plt.axes(axs[0])
hist_data.plotHeatmap()
plt.text(0.95, 0.95, "data", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
plt.axes(axs[1])
hist_sim.plotHeatmap()
plt.text(0.95, 0.95, "simulation", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
for i in range(2):
    plt.axes(axs[i])
    plt.plot([0,10], [2,2], '-', color='red')
    plt.plot([0.4,0.4], [0,20], '-', color='red')
    plt.xlim(0, 10)
    plt.ylim(0, 20)
    plt.yticks(np.arange(0, 21, 2))
    plt.xlabel(r"$p_{K^-}$ (GeV/c)")
    plt.ylabel(r"$\theta_{K^-}$ (deg)")
file_pdf.savefig()
plt.close()

# d kinematics
print("d kinematics")
fig = plt.figure(figsize=(16, 6), dpi=300)
gs = fig.add_gridspec(1, 2)
axs = gs.subplots()
hist_data = file_data.get('KinematicsCut/d_kinematics_meas_KinematicsCut')
hist_sim = file_sim.get('KinematicsCut/d_kinematics_meas_KinematicsCut')
hist_sim.scale(0.02)
plt.axes(axs[0])
hist_data.plotHeatmap()
plt.text(0.95, 0.95, "data", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
plt.axes(axs[1])
hist_sim.plotHeatmap()
plt.text(0.95, 0.95, "simulation", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
for i in range(2):
    plt.axes(axs[i])
    plt.plot([0,10], [2,2], '-', color='red')
    plt.plot([0.4,0.4], [0,180], '-', color='red')
    plt.xlim(0, 2)
    plt.ylim(0, 180)
    plt.xlabel(r"$p_{d}$ (GeV/c)")
    plt.ylabel(r"$\theta_{d}$ (deg)")
file_pdf.savefig()
plt.close()

# deuteron CDC dE/dx
print("deuteron CDC dE/dx")
fig = plt.figure(figsize=(16, 6), dpi=300)
gs = fig.add_gridspec(1, 2)
axs = gs.subplots()
hist_data = file_data.get('dEdxCut/d_dEdx_cdc_meas_dEdxCut')
hist_sim = file_sim.get('dEdxCut/d_dEdx_cdc_meas_dEdxCut')
hist_sim.scale(0.02)
plt.axes(axs[0])
hist_data.plotHeatmap(vmin=0, vmax=50)
plt.text(0.95, 0.95, "data", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
plt.axes(axs[1])
hist_sim.plotHeatmap(vmin=0, vmax=50)
plt.text(0.95, 0.95, "simulation", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
for i in range(2):
    plt.axes(axs[i])
    plt.plot(np.arange(0.25, 3, 0.01), np.exp(-3.3*np.arange(0.25, 3, 0.01)+4.1)+2.3, color='red')
    plt.xlim(0, 2)
    plt.ylim(0, 40)
    plt.xlabel(r"$p_d$ (GeV/c)")
    plt.ylabel(r"$(dE/dx)^{\mathrm{CDC}}_d$ (keV/cm)")
file_pdf.savefig()
plt.close()

# Vertex x and y
print("Vertex x and y")
fig = plt.figure(figsize=(16, 7), dpi=300)
gs = fig.add_gridspec(1, 2)
axs = gs.subplots()
hist_data = file_data.get('VertexCut/vertex_x_y_kin_VertexCut')
hist_sim = file_sim.get('VertexCut/vertex_x_y_kin_VertexCut')
hist_sim.scale(0.02)
plt.axes(axs[0])
hist_data.plotHeatmap(vmin=0, vmax=100)
plt.plot(np.cos(np.linspace(0, 2*np.pi, 100)), np.sin(np.linspace(0, 2*np.pi, 100)), '-', color='red')
plt.text(0.95, 0.95, "data", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
plt.axes(axs[1])
hist_sim.plotHeatmap(vmin=0, vmax=100)
plt.plot(np.cos(np.linspace(0, 2*np.pi, 100)), np.sin(np.linspace(0, 2*np.pi, 100)), '-', color='red')
plt.text(0.95, 0.95, "simulation", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
for i in range(2):
    plt.axes(axs[i])
    plt.xlim(-2, 2)
    plt.ylim(-2, 2)
    plt.xlabel(r"Vertex $x$ (cm)")
    plt.ylabel(r"Vertex $y$ (cm)")
file_pdf.savefig()
plt.close()

# Vertex z
print("Vertex z")
fig = plt.figure(figsize=(8, 6), dpi=300)
hist_data = file_data.get('VertexCut/vertex_z_kin_VertexCut')
hist_sim = file_sim.get('VertexCut/vertex_z_kin_VertexCut')
hist_sim.scale(0.0175)
hist_data.plotPoints(label="Data", marker='o', markersize=3, linestyle='None', color='black')
hist_sim.plotPoints(label="Sim", marker='o', markersize=3, linestyle='None', color='blue')
plt.plot([51, 51], [0, 400], '-', color='red')
plt.plot([79, 79], [0, 400], '-', color='red')
plt.xlim(40, 90)
plt.ylim(0, 400)
plt.xlabel(r"$M_{K^+K^-} (GeV/c^2)$")
plt.ylabel("Counts")
plt.legend()
file_pdf.savefig()
plt.close()

# Missing p minus
print("Missing p minus")
fig = plt.figure(figsize=(8, 6), dpi=300)
hist_data = file_data.get('MissPMinusCut/miss_pminus_meas_MissPMinusCut')
hist_sim = file_sim.get('MissPMinusCut/miss_pminus_meas_MissPMinusCut')
hist_sim.scale(0.019)
hist_data.plotPoints(label="Data", marker='o', markersize=3, linestyle='None', color='black')
hist_sim.plotPoints(label="Sim", marker='o', markersize=3, linestyle='None', color='blue')
plt.plot([-0.02, -0.02], [0, 700], '-', color='red')
plt.xlim(-0.2, 0.2)
plt.ylim(0, 700)
plt.xlabel(r"$p^-_{\rm miss}$ (GeV/c)")
plt.ylabel("Counts")
plt.legend()
file_pdf.savefig()
plt.close()

# KinFit Chi2
print("KinFit Chi2")
fig = plt.figure(figsize=(8, 6), dpi=300)
hist_data = file_data.get('KinFitChiSqCut/chisq_per_ndf_kin_KinFitChiSqCut')
hist_sim = file_sim.get('KinFitChiSqCut/chisq_per_ndf_kin_KinFitChiSqCut')
hist_sim.scale(0.015)
hist_data.plotPoints(label="Data", marker='o', markersize=3, linestyle='None', color='black')
hist_sim.plotPoints(label="Sim", marker='o', markersize=3, linestyle='None', color='blue')
plt.plot([5, 5], [0, 4000], '-', color='red')
plt.xlim(0, 10)
plt.ylim(0, 4000)
plt.xlabel(r"$\chi^{2}$/NDF")
plt.ylabel("Counts")
plt.legend()
file_pdf.savefig()
plt.close()

# K+K- invariant mass
print("K+K- invariant mass")
fig = plt.figure(figsize=(8, 6), dpi=300)
hist_data = file_data.get('NominalCut/phi_mass_kin_NominalCut')
hist_sim = file_sim.get('NominalCut/phi_mass_kin_NominalCut')
hist_sim.scale(0.0175)
hist_data.plotPoints(label="Data", marker='o', markersize=3, linestyle='None', color='black')
hist_sim.plotPoints(label="Sim", marker='o', markersize=3, linestyle='None', color='blue')
plt.plot([1.005, 1.005], [0, 3000], '-', color='red')
plt.plot([1.04, 1.04], [0, 3000], '-', color='red')
plt.xlim(0.98, 1.1)
plt.ylim(0, 3000)
plt.xlabel(r"$M_{K^+K^-} (GeV/c^2)$")
plt.ylabel("Counts")
plt.legend()
file_pdf.savefig()
plt.close()

###################################################################### BEAM PHOTON #####################################################################################

# Beam energy
print("Beam energy")
fig = plt.figure(figsize=(8, 6), dpi=300)
hist_data = file_data.get('PlotCut/beam_energy_PlotCut')
hist_sim = file_sim.get('PlotCut/beam_energy_PlotCut')
hist_sim.scale(0.017)
hist_data.plotPoints(label="Data", marker='o', markersize=3, linestyle='None', color='black')
hist_sim.plotPoints(label="Sim", marker='o', markersize=3, linestyle='None', color='blue')
plt.bar(hist_data.x, hist_data.y, width=0.1, alpha=0.5, label='Data', color='green')
plt.xlim(5, 11)
plt.xlabel(r"Beam $E$ (GeV)")
plt.ylabel("Counts")
plt.legend()
file_pdf.savefig()
plt.close()

# Beam Timing
print("Beam timing")
fig = plt.figure(figsize=(8, 6), dpi=300)
hist_data = file_data.get('PlotCut/beam_DeltaT_PlotCut')
hist_sim = file_sim.get('PlotCut/beam_DeltaT_PlotCut')
hist_sim.scale(0.005)
hist_data.plotPoints(label="Data", marker='o', markersize=3, linestyle='None', color='black')
hist_sim.plotPoints(label="Sim", marker='o', markersize=3, linestyle='None', color='blue')
plt.xlim(-20, 20)
plt.xlabel(r"Beam $\Delta t$ (ns)")
plt.ylabel("Counts")
plt.legend()
file_pdf.savefig()
plt.close()

###################################################################### K PLUS #####################################################################################

# K+ PID FOM
print("K+ PID FOM")
fig = plt.figure(figsize=(8, 6), dpi=300)
hist_data = file_data.get('PlotCut/kp_pidfom_PlotCut')
hist_sim = file_sim.get('PlotCut/kp_pidfom_PlotCut')
hist_sim.scale(0.02)
hist_data.plotPoints(label="Data", marker='o', markersize=3, linestyle='None', color='black')
hist_sim.plotPoints(label="Sim", marker='o', markersize=3, linestyle='None', color='blue')
plt.xlim(0, 1)
plt.xlabel(r"$K^+$ PID FOM")
plt.ylabel("Counts")
plt.legend()
file_pdf.savefig()
plt.close()

# K+ timing
print("K+ timing")
fig = plt.figure(figsize=(8, 6), dpi=300)
hist_data = file_data.get('PlotCut/kp_DeltaT_meas_PlotCut')
hist_sim = file_sim.get('PlotCut/kp_DeltaT_meas_PlotCut')
hist_sim.scale(0.017)
hist_data.plotPoints(label="Data", marker='o', markersize=3, linestyle='None', color='black')
hist_sim.plotPoints(label="Sim", marker='o', markersize=3, linestyle='None', color='blue')
plt.xlim(-2, 2)
plt.xlabel(r"$K^+ \Delta t$ (ns)")
plt.ylabel("Counts")
plt.legend()
file_pdf.savefig()
plt.close()

# K+ timing vs p
print("K+ timing vs p")
fig = plt.figure(figsize=(16, 6), dpi=300)
gs = fig.add_gridspec(1, 2)
axs = gs.subplots()
hist_data = file_data.get('PlotCut/kp_DeltaT_momentum_meas_PlotCut')
hist_sim = file_sim.get('PlotCut/kp_DeltaT_momentum_meas_PlotCut')
hist_sim.scale(0.02)
plt.axes(axs[0])
hist_data.plotHeatmap()
plt.text(0.95, 0.95, "data", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
plt.axes(axs[1])
hist_sim.plotHeatmap()
plt.text(0.95, 0.95, "simulation", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
for i in range(2):
    plt.axes(axs[i])
    plt.xlim(0, 10)
    plt.ylim(-2, 2)
    plt.xlabel(r"$p_{K^+}$ (GeV/c)")
    plt.ylabel(r"$\Delta t_{K^+}$ (ns)")
file_pdf.savefig()
plt.close()

# K+ CDC dE/dx
print("K+ CDC dE/dx")
fig = plt.figure(figsize=(16, 6), dpi=300)
gs = fig.add_gridspec(1, 2)
axs = gs.subplots()
hist_data = file_data.get('PlotCut/kp_dEdx_cdc_meas_PlotCut')
hist_sim = file_sim.get('PlotCut/kp_dEdx_cdc_meas_PlotCut')
hist_sim.scale(0.02)
plt.axes(axs[0])
hist_data.plotHeatmap()
plt.text(0.95, 0.95, "data", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
plt.axes(axs[1])
hist_sim.plotHeatmap()
plt.text(0.95, 0.95, "simulation", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
for i in range(2):
    plt.axes(axs[i])
    plt.xlim(0, 10)
    plt.ylim(0, 40)
    plt.xlabel(r"$p_{K^+}$ (GeV/c)")
    plt.ylabel(r"$(dE/dx)_{K^+}^{\mathrm{CDC}}$ (keV/cm)")
file_pdf.savefig()
plt.close()

# K+ FDC dE/dx
print("K+ FDC dE/dx")
fig = plt.figure(figsize=(16, 6), dpi=300)
gs = fig.add_gridspec(1, 2)
axs = gs.subplots()
hist_data = file_data.get('PlotCut/kp_dEdx_fdc_meas_PlotCut')
hist_sim = file_sim.get('PlotCut/kp_dEdx_fdc_meas_PlotCut')
hist_sim.scale(0.02)
plt.axes(axs[0])
hist_data.plotHeatmap()
plt.text(0.95, 0.95, "data", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
plt.axes(axs[1])
hist_sim.plotHeatmap()
plt.text(0.95, 0.95, "simulation", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
for i in range(2):
    plt.axes(axs[i])
    plt.xlim(0, 10)
    plt.ylim(0, 40)
    plt.xlabel(r"$p_{K^+}$ (GeV/c)")
    plt.ylabel(r"$(dE/dx)_{K^+}^{\mathrm{FDC}}$ (keV/cm)")
file_pdf.savefig()
plt.close()

# K+ TOF dE/dx
print("K+ TOF dE/dx")
fig = plt.figure(figsize=(16, 6), dpi=300)
gs = fig.add_gridspec(1, 2)
axs = gs.subplots()
hist_data = file_data.get('PlotCut/kp_dEdx_tof_meas_PlotCut')
hist_sim = file_sim.get('PlotCut/kp_dEdx_tof_meas_PlotCut')
hist_sim.scale(0.02)
plt.axes(axs[0])
hist_data.plotHeatmap()
plt.text(0.95, 0.95, "data", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
plt.axes(axs[1])
hist_sim.plotHeatmap()
plt.text(0.95, 0.95, "simulation", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
for i in range(2):
    plt.axes(axs[i])
    plt.xlim(0, 10)
    plt.ylim(0, 40)
    plt.xlabel(r"$p_{K^+}$ (GeV/c)")
    plt.ylabel(r"$(dE/dx)_{K^+}^{\mathrm{TOF}}$ (keV/cm)")
file_pdf.savefig()
plt.close()

# K+ ST dE/dx
print("K+ ST dE/dx")
fig = plt.figure(figsize=(16, 6), dpi=300)
gs = fig.add_gridspec(1, 2)
axs = gs.subplots()
hist_data = file_data.get('PlotCut/kp_dEdx_st_meas_PlotCut')
hist_sim = file_sim.get('PlotCut/kp_dEdx_st_meas_PlotCut')
hist_sim.scale(0.02)
plt.axes(axs[0])
hist_data.plotHeatmap()
plt.text(0.95, 0.95, "data", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
plt.axes(axs[1])
hist_sim.plotHeatmap()
plt.text(0.95, 0.95, "simulation", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
for i in range(2):
    plt.axes(axs[i])
    plt.xlim(0, 10)
    plt.ylim(0, 40)
    plt.xlabel(r"$p_{K^+}$ (GeV/c)")
    plt.ylabel(r"$(dE/dx)_{K^+}^{\mathrm{ST}}$ (keV/cm)")
file_pdf.savefig()
plt.close()

# K+ kinematics
print("K+ kinematics")
fig = plt.figure(figsize=(16, 6), dpi=300)
gs = fig.add_gridspec(1, 2)
axs = gs.subplots()
hist_data = file_data.get('PlotCut/kp_kinematics_meas_PlotCut')
hist_sim = file_sim.get('PlotCut/kp_kinematics_meas_PlotCut')
hist_sim.scale(0.02)
plt.axes(axs[0])
hist_data.plotHeatmap()
plt.text(0.95, 0.95, "data", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
plt.axes(axs[1])
hist_sim.plotHeatmap()
plt.text(0.95, 0.95, "simulation", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
for i in range(2):
    plt.axes(axs[i])
    plt.plot([0,10], [2,2], '-', color='red')
    plt.plot([0.4,0.4], [0,20], '-', color='red')
    plt.xlim(0, 10)
    plt.ylim(0, 20)
    plt.yticks(np.arange(0, 21, 2))
    plt.xlabel(r"$p_{K^+}$ (GeV/c)")
    plt.ylabel(r"$\theta_{K^+}$ (deg)")
file_pdf.savefig()
plt.close()

# K+ kinematics in FDC only
print("K+ kinematics in FDC only")
fig = plt.figure(figsize=(16, 6), dpi=300)
gs = fig.add_gridspec(1, 2)
axs = gs.subplots()
hist_data = file_data.get('PlotCut/kp_kinematics_fdc_meas_PlotCut')
hist_sim = file_sim.get('PlotCut/kp_kinematics_fdc_meas_PlotCut')
hist_sim.scale(0.02)
plt.axes(axs[0])
hist_data.plotHeatmap()
plt.text(0.95, 0.95, "data", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
plt.axes(axs[1])
hist_sim.plotHeatmap()
plt.text(0.95, 0.95, "simulation", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
for i in range(2):
    plt.axes(axs[i])
    plt.plot([0,10], [2,2], '-', color='red')
    plt.plot([0.4,0.4], [0,20], '-', color='red')
    plt.xlim(0, 10)
    plt.ylim(0, 20)
    plt.yticks(np.arange(0, 21, 2))
    plt.xlabel(r"$p_{K^+}$ (GeV/c)")
    plt.ylabel(r"$\theta_{K^+}$ (deg)")
file_pdf.savefig()
plt.close()

# K+ kinematics in FDC and CDC
print("K+ kinematics in FDC and CDC")
fig = plt.figure(figsize=(16, 6), dpi=300)
gs = fig.add_gridspec(1, 2)
axs = gs.subplots()
hist_data = file_data.get('PlotCut/kp_kinematics_fdc_cdc_meas_PlotCut')
hist_sim = file_sim.get('PlotCut/kp_kinematics_fdc_cdc_meas_PlotCut')
hist_sim.scale(0.02)
plt.axes(axs[0])
hist_data.plotHeatmap()
plt.text(0.95, 0.95, "data", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
plt.axes(axs[1])
hist_sim.plotHeatmap()
plt.text(0.95, 0.95, "simulation", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
for i in range(2):
    plt.axes(axs[i])
    plt.plot([0,10], [2,2], '-', color='red')
    plt.plot([0.4,0.4], [0,20], '-', color='red')
    plt.xlim(0, 10)
    plt.ylim(0, 20)
    plt.yticks(np.arange(0, 21, 2))
    plt.xlabel(r"$p_{K^+}$ (GeV/c)")
    plt.ylabel(r"$\theta_{K^+}$ (deg)")
file_pdf.savefig()
plt.close()

# K+ kinematics in CDC only
print("K+ kinematics in CDC only")
fig = plt.figure(figsize=(16, 6), dpi=300)
gs = fig.add_gridspec(1, 2)
axs = gs.subplots()
hist_data = file_data.get('PlotCut/kp_kinematics_cdc_meas_PlotCut')
hist_sim = file_sim.get('PlotCut/kp_kinematics_cdc_meas_PlotCut')
hist_sim.scale(0.02)
plt.axes(axs[0])
hist_data.plotHeatmap()
plt.text(0.95, 0.95, "data", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
plt.axes(axs[1])
hist_sim.plotHeatmap()
plt.text(0.95, 0.95, "simulation", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
for i in range(2):
    plt.axes(axs[i])
    plt.plot([0,10], [2,2], '-', color='red')
    plt.plot([0.4,0.4], [0,20], '-', color='red')
    plt.xlim(0, 10)
    plt.ylim(0, 20)
    plt.yticks(np.arange(0, 21, 2))
    plt.xlabel(r"$p_{K^+}$ (GeV/c)")
    plt.ylabel(r"$\theta_{K^+}$ (deg)")
file_pdf.savefig()
plt.close()

###################################################################### K MINUS #####################################################################################

# K- PID FOM
print("K- PID FOM")
fig = plt.figure(figsize=(8, 6), dpi=300)
hist_data = file_data.get('PlotCut/km_pidfom_PlotCut')
hist_sim = file_sim.get('PlotCut/km_pidfom_PlotCut')
hist_sim.scale(0.02)
hist_data.plotPoints(label="Data", marker='o', markersize=3, linestyle='None', color='black')
hist_sim.plotPoints(label="Sim", marker='o', markersize=3, linestyle='None', color='blue')
plt.xlim(0, 1)
plt.xlabel(r"$K^-$ PID FOM")
plt.ylabel("Counts")
plt.legend()
file_pdf.savefig()
plt.close()

# K- timing
print("K- timing")
fig = plt.figure(figsize=(8, 6), dpi=300)
hist_data = file_data.get('PlotCut/km_DeltaT_meas_PlotCut')
hist_sim = file_sim.get('PlotCut/km_DeltaT_meas_PlotCut')
hist_sim.scale(0.017)
hist_data.plotPoints(label="Data", marker='o', markersize=3, linestyle='None', color='black')
hist_sim.plotPoints(label="Sim", marker='o', markersize=3, linestyle='None', color='blue')
plt.xlim(-2, 2)
plt.xlabel(r"$K^-$ $\Delta t$ (ns)")
plt.ylabel("Counts")
plt.legend()
file_pdf.savefig()
plt.close()

# K- timing vs p
print("K- timing vs p")
fig = plt.figure(figsize=(16, 6), dpi=300)
gs = fig.add_gridspec(1, 2)
axs = gs.subplots()
hist_data = file_data.get('PlotCut/km_DeltaT_momentum_meas_PlotCut')
hist_sim = file_sim.get('PlotCut/km_DeltaT_momentum_meas_PlotCut')
hist_sim.scale(0.02)
plt.axes(axs[0])
hist_data.plotHeatmap()
plt.text(0.95, 0.95, "data", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
plt.axes(axs[1])
hist_sim.plotHeatmap()
plt.text(0.95, 0.95, "simulation", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
for i in range(2):
    plt.axes(axs[i])
    plt.xlim(0, 10)
    plt.ylim(-2, 2)
    plt.xlabel(r"$p_{K^-}$ (GeV/c)")
    plt.ylabel(r"$\Delta t_{K^-}$ (ns)")
file_pdf.savefig()
plt.close()

# K- CDC dE/dx
print("K- CDC dE/dx")
fig = plt.figure(figsize=(16, 6), dpi=300)
gs = fig.add_gridspec(1, 2)
axs = gs.subplots()
hist_data = file_data.get('PlotCut/km_dEdx_cdc_meas_PlotCut')
hist_sim = file_sim.get('PlotCut/km_dEdx_cdc_meas_PlotCut')
hist_sim.scale(0.02)
plt.axes(axs[0])
hist_data.plotHeatmap()
plt.text(0.95, 0.95, "data", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
plt.axes(axs[1])
hist_sim.plotHeatmap()
plt.text(0.95, 0.95, "simulation", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
for i in range(2):
    plt.axes(axs[i])
    plt.xlim(0, 10)
    plt.ylim(0, 40)
    plt.xlabel(r"$p_{K^-}$ (GeV/c)")
    plt.ylabel(r"$(dE/dx)_{K^-}^{\mathrm{CDC}}$ (keV/cm)")
file_pdf.savefig()
plt.close()

# K- FDC dE/dx
print("K- FDC dE/dx")
fig = plt.figure(figsize=(16, 6), dpi=300)
gs = fig.add_gridspec(1, 2)
axs = gs.subplots()
hist_data = file_data.get('PlotCut/km_dEdx_fdc_meas_PlotCut')
hist_sim = file_sim.get('PlotCut/km_dEdx_fdc_meas_PlotCut')
hist_sim.scale(0.02)
plt.axes(axs[0])
hist_data.plotHeatmap()
plt.text(0.95, 0.95, "data", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
plt.axes(axs[1])
hist_sim.plotHeatmap()
plt.text(0.95, 0.95, "simulation", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
for i in range(2):
    plt.axes(axs[i])
    plt.xlim(0, 10)
    plt.ylim(0, 40)
    plt.xlabel(r"$p_{K^-}$ (GeV/c)")
    plt.ylabel(r"$(dE/dx)_{K^-}^{\mathrm{FDC}}$ (keV/cm)")
file_pdf.savefig()
plt.close()

# K- TOF dE/dx
print("K- TOF dE/dx")
fig = plt.figure(figsize=(16, 6), dpi=300)
gs = fig.add_gridspec(1, 2)
axs = gs.subplots()
hist_data = file_data.get('PlotCut/km_dEdx_tof_meas_PlotCut')
hist_sim = file_sim.get('PlotCut/km_dEdx_tof_meas_PlotCut')
hist_sim.scale(0.02)
plt.axes(axs[0])
hist_data.plotHeatmap()
plt.text(0.95, 0.95, "data", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
plt.axes(axs[1])
hist_sim.plotHeatmap()
plt.text(0.95, 0.95, "simulation", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
for i in range(2):
    plt.axes(axs[i])
    plt.xlim(0, 10)
    plt.ylim(0, 40)
    plt.xlabel(r"$p_{K^-}$ (GeV/c)")
    plt.ylabel(r"$(dE/dx)_{K^-}^{\mathrm{TOF}}$ (keV/cm)")
file_pdf.savefig()
plt.close()

# K- ST dE/dx
print("K- ST dE/dx")
fig = plt.figure(figsize=(16, 6), dpi=300)
gs = fig.add_gridspec(1, 2)
axs = gs.subplots()
hist_data = file_data.get('PlotCut/km_dEdx_st_meas_PlotCut')
hist_sim = file_sim.get('PlotCut/km_dEdx_st_meas_PlotCut')
hist_sim.scale(0.02)
plt.axes(axs[0])
hist_data.plotHeatmap()
plt.text(0.95, 0.95, "data", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
plt.axes(axs[1])
hist_sim.plotHeatmap()
plt.text(0.95, 0.95, "simulation", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
for i in range(2):
    plt.axes(axs[i])
    plt.xlim(0, 10)
    plt.ylim(0, 40)
    plt.xlabel(r"$p_{K^-}$ (GeV/c)")
    plt.ylabel(r"$(dE/dx)_{K^-}^{\mathrm{ST}}$ (keV/cm)")
file_pdf.savefig()
plt.close()

# K- kinematics
print("K- kinematics")
fig = plt.figure(figsize=(16, 6), dpi=300)
gs = fig.add_gridspec(1, 2)
axs = gs.subplots()
hist_data = file_data.get('PlotCut/km_kinematics_meas_PlotCut')
hist_sim = file_sim.get('PlotCut/km_kinematics_meas_PlotCut')
hist_sim.scale(0.02)
plt.axes(axs[0])
hist_data.plotHeatmap()
plt.text(0.95, 0.95, "data", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
plt.axes(axs[1])
hist_sim.plotHeatmap()
plt.text(0.95, 0.95, "simulation", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
for i in range(2):
    plt.axes(axs[i])
    plt.plot([0,10], [2,2], '-', color='red')
    plt.plot([0.4,0.4], [0,20], '-', color='red')
    plt.xlim(0, 10)
    plt.ylim(0, 20)
    plt.yticks(np.arange(0, 21, 2))
    plt.xlabel(r"$p_{K^-}$ (GeV/c)")
    plt.ylabel(r"$\theta_{K^-}$ (deg)")
file_pdf.savefig()
plt.close()

# K- kinematics in FDC only
print("K- kinematics in FDC only")
fig = plt.figure(figsize=(16, 6), dpi=300)
gs = fig.add_gridspec(1, 2)
axs = gs.subplots()
hist_data = file_data.get('PlotCut/km_kinematics_fdc_meas_PlotCut')
hist_sim = file_sim.get('PlotCut/km_kinematics_fdc_meas_PlotCut')
hist_sim.scale(0.02)
plt.axes(axs[0])
hist_data.plotHeatmap()
plt.text(0.95, 0.95, "data", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
plt.axes(axs[1])
hist_sim.plotHeatmap()
plt.text(0.95, 0.95, "simulation", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
for i in range(2):
    plt.axes(axs[i])
    plt.plot([0,10], [2,2], '-', color='red')
    plt.plot([0.4,0.4], [0,20], '-', color='red')
    plt.xlim(0, 10)
    plt.ylim(0, 20)
    plt.yticks(np.arange(0, 21, 2))
    plt.xlabel(r"$p_{K^-}$ (GeV/c)")
    plt.ylabel(r"$\theta_{K^-}$ (deg)")
file_pdf.savefig()
plt.close()

# K- kinematics in FDC and CDC
print("K- kinematics in FDC and CDC")
fig = plt.figure(figsize=(16, 6), dpi=300)
gs = fig.add_gridspec(1, 2)
axs = gs.subplots()
hist_data = file_data.get('PlotCut/km_kinematics_fdc_cdc_meas_PlotCut')
hist_sim = file_sim.get('PlotCut/km_kinematics_fdc_cdc_meas_PlotCut')
hist_sim.scale(0.02)
plt.axes(axs[0])
hist_data.plotHeatmap()
plt.text(0.95, 0.95, "data", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
plt.axes(axs[1])
hist_sim.plotHeatmap()
plt.text(0.95, 0.95, "simulation", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
for i in range(2):
    plt.axes(axs[i])
    plt.plot([0,10], [2,2], '-', color='red')
    plt.plot([0.4,0.4], [0,20], '-', color='red')
    plt.xlim(0, 10)
    plt.ylim(0, 20)
    plt.yticks(np.arange(0, 21, 2))
    plt.xlabel(r"$p_{K^-}$ (GeV/c)")
    plt.ylabel(r"$\theta_{K^-}$ (deg)")
file_pdf.savefig()
plt.close()

# K- kinematics in CDC only
print("K- kinematics in CDC only")
fig = plt.figure(figsize=(16, 6), dpi=300)
gs = fig.add_gridspec(1, 2)
axs = gs.subplots()
hist_data = file_data.get('PlotCut/km_kinematics_cdc_meas_PlotCut')
hist_sim = file_sim.get('PlotCut/km_kinematics_cdc_meas_PlotCut')
hist_sim.scale(0.02)
plt.axes(axs[0])
hist_data.plotHeatmap()
plt.text(0.95, 0.95, "data", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
plt.axes(axs[1])
hist_sim.plotHeatmap()
plt.text(0.95, 0.95, "simulation", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
for i in range(2):
    plt.axes(axs[i])
    plt.plot([0,10], [2,2], '-', color='red')
    plt.plot([0.4,0.4], [0,20], '-', color='red')
    plt.xlim(0, 10)
    plt.ylim(0, 20)
    plt.yticks(np.arange(0, 21, 2))
    plt.xlabel(r"$p_{K^-}$ (GeV/c)")
    plt.ylabel(r"$\theta_{K^-}$ (deg)")
file_pdf.savefig()
plt.close()

###################################################################### DEUTERON #####################################################################################

# d timing
print("d timing")
fig = plt.figure(figsize=(8, 6), dpi=300)
hist_data = file_data.get('PlotCut/d_DeltaT_meas_PlotCut')
hist_sim = file_sim.get('PlotCut/d_DeltaT_meas_PlotCut')
hist_sim.scale(0.0175)
hist_data.plotPoints(label="Data", marker='o', markersize=3, linestyle='None', color='black')
hist_sim.plotPoints(label="Sim", marker='o', markersize=3, linestyle='None', color='blue')
plt.xlim(-2, 2)
plt.xlabel(r"$d \ \Delta t$ (ns)")
plt.ylabel("Counts")
plt.legend()
file_pdf.savefig()
plt.close()

# d timing vs p
print("d timing vs p")
fig = plt.figure(figsize=(16, 6), dpi=300)
gs = fig.add_gridspec(1, 2)
axs = gs.subplots()
hist_data = file_data.get('PlotCut/d_DeltaT_momentum_meas_PlotCut')
hist_sim = file_sim.get('PlotCut/d_DeltaT_momentum_meas_PlotCut')
hist_sim.scale(0.02)
plt.axes(axs[0])
hist_data.plotHeatmap()
plt.text(0.95, 0.95, "data", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
plt.axes(axs[1])
hist_sim.plotHeatmap()
plt.text(0.95, 0.95, "simulation", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
for i in range(2):
    plt.axes(axs[i])
    plt.xlim(0, 2)
    plt.ylim(-2, 2)
    plt.xlabel(r"$p_d$ (GeV/c)")
    plt.ylabel(r"$d \ \Delta t$ (ns)")
file_pdf.savefig()
plt.close()

# d CDC dE/dx
print("d CDC dE/dx")
fig = plt.figure(figsize=(16, 6), dpi=300)
gs = fig.add_gridspec(1, 2)
axs = gs.subplots()
hist_data = file_data.get('PlotCut/d_dEdx_cdc_meas_PlotCut')
hist_sim = file_sim.get('PlotCut/d_dEdx_cdc_meas_PlotCut')
hist_sim.scale(0.02)
plt.axes(axs[0])
hist_data.plotHeatmap()
plt.text(0.95, 0.95, "data", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
plt.axes(axs[1])
hist_sim.plotHeatmap()
plt.text(0.95, 0.95, "simulation", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
for i in range(2):
    plt.axes(axs[i])
    plt.xlim(0, 2)
    plt.ylim(0, 40)
    plt.xlabel(r"$p_d$ (GeV/c)")
    plt.ylabel(r"$(dE/dx)_d^{\mathrm{CDC}}$ (keV/cm)")
file_pdf.savefig()
plt.close()

# d FDC dE/dx
print("d FDC dE/dx")
fig = plt.figure(figsize=(16, 6), dpi=300)
gs = fig.add_gridspec(1, 2)
axs = gs.subplots()
hist_data = file_data.get('PlotCut/d_dEdx_fdc_meas_PlotCut')
hist_sim = file_sim.get('PlotCut/d_dEdx_fdc_meas_PlotCut')
hist_sim.scale(0.02)
plt.axes(axs[0])
hist_data.plotHeatmap()
plt.text(0.95, 0.95, "data", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
plt.axes(axs[1])
hist_sim.plotHeatmap()
plt.text(0.95, 0.95, "simulation", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
for i in range(2):
    plt.axes(axs[i])
    plt.xlim(0, 2)
    plt.ylim(0, 40)
    plt.xlabel(r"$p_d$ (GeV/c)")
    plt.ylabel(r"$(dE/dx)_d^{\mathrm{FDC}}$ (keV/cm)")
file_pdf.savefig()
plt.close()

# d TOF dE/dx
print("d TOF dE/dx")
fig = plt.figure(figsize=(16, 6), dpi=300)
gs = fig.add_gridspec(1, 2)
axs = gs.subplots()
hist_data = file_data.get('PlotCut/d_dEdx_tof_meas_PlotCut')
hist_sim = file_sim.get('PlotCut/d_dEdx_tof_meas_PlotCut')
hist_sim.scale(0.02)
plt.axes(axs[0])
hist_data.plotHeatmap()
plt.text(0.95, 0.95, "data", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
plt.axes(axs[1])
hist_sim.plotHeatmap()
plt.text(0.95, 0.95, "simulation", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
for i in range(2):
    plt.axes(axs[i])
    plt.xlim(0, 2)
    plt.ylim(0, 40)
    plt.xlabel(r"$p_d$ (GeV/c)")
    plt.ylabel(r"$(dE/dx)_d^{\mathrm{TOF}}$ (keV/cm)")
file_pdf.savefig()
plt.close()

# d ST dE/dx
print("d ST dE/dx")
fig = plt.figure(figsize=(16, 6), dpi=300)
gs = fig.add_gridspec(1, 2)
axs = gs.subplots()
hist_data = file_data.get('PlotCut/d_dEdx_st_meas_PlotCut')
hist_sim = file_sim.get('PlotCut/d_dEdx_st_meas_PlotCut')
hist_sim.scale(0.02)
plt.axes(axs[0])
hist_data.plotHeatmap()
plt.text(0.95, 0.95, "data", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
plt.axes(axs[1])
hist_sim.plotHeatmap()
plt.text(0.95, 0.95, "simulation", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
for i in range(2):
    plt.axes(axs[i])
    plt.xlim(0, 2)
    plt.ylim(0, 40)
    plt.xlabel(r"$p_d$ (GeV/c)")
    plt.ylabel(r"$(dE/dx)_d^{\mathrm{ST}}$ (keV/cm)")
file_pdf.savefig()
plt.close()

# d dE/dx in CDC vs ST
print("d dE/dx in CDC vs ST")
fig = plt.figure(figsize=(16, 6), dpi=300)
gs = fig.add_gridspec(1, 2)
axs = gs.subplots()
hist_data = file_data.get('PlotCut/d_dEdx_cdc_st_meas_PlotCut')
hist_sim = file_sim.get('PlotCut/d_dEdx_cdc_st_meas_PlotCut')
hist_sim.scale(0.02)
plt.axes(axs[0])
hist_data.plotHeatmap()
plt.text(0.95, 0.95, "data", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
plt.axes(axs[1])
hist_sim.plotHeatmap()
plt.text(0.95, 0.95, "simulation", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
for i in range(2):
    plt.axes(axs[i])
    plt.xlim(0, 40)
    plt.ylim(0, 40)
    plt.xlabel(r"$(dE/dx)_{d}^{\mathrm{CDC}}$ (keV/cm)")
    plt.ylabel(r"$(dE/dx)_{d}^{\mathrm{ST}}$ (keV/cm)")
file_pdf.savefig()
plt.close()

# d kinematics
print("d kinematics")
fig = plt.figure(figsize=(16, 6), dpi=300)
gs = fig.add_gridspec(1, 2)
axs = gs.subplots()
hist_data = file_data.get('PlotCut/d_kinematics_meas_PlotCut')
hist_sim = file_sim.get('PlotCut/d_kinematics_meas_PlotCut')
hist_sim.scale(0.02)
plt.axes(axs[0])
hist_data.plotHeatmap()
plt.text(0.95, 0.95, "data", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
plt.axes(axs[1])
hist_sim.plotHeatmap()
plt.text(0.95, 0.95, "simulation", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
for i in range(2):
    plt.axes(axs[i])
    plt.xlim(0, 2)
    plt.ylim(0, 90)
    plt.yticks(np.arange(0, 91, 10))
    plt.xlabel(r"$p_{d}$ (GeV/c)")
    plt.ylabel(r"$\theta_{d}$ (deg)")
file_pdf.savefig()
plt.close()

###################################################################### PHI MESON #####################################################################################

# phi mass
print("Phi mass")
fig = plt.figure(figsize=(8, 6), dpi=300)
hist_data = file_data.get('PlotCut/phi_mass_kin_PlotCut')
hist_sim = file_sim.get('PlotCut/phi_mass_kin_PlotCut')
hist_sim.scale(0.017)
hist_data.plotPoints(label="Data", marker='o', markersize=3, linestyle='None', color='black')
hist_sim.plotPoints(label="Sim", marker='o', markersize=3, linestyle='-', color='blue')
plt.xlim(0.9, 1.1)
plt.xlabel(r"$m_{K^+ K^-}$ (GeV/$c$)" )
plt.ylabel("Counts")
plt.legend()
file_pdf.savefig()
plt.close()

# phi mass vs KinFit chi2
print("Phi mass vs KinFit chi2")
fig = plt.figure(figsize=(16, 6), dpi=300)
gs = fig.add_gridspec(1, 2)
axs = gs.subplots()
hist_data = file_data.get('PlotCut/phi_mass_chisq_kin_PlotCut')
hist_sim = file_sim.get('PlotCut/phi_mass_chisq_kin_PlotCut')
hist_sim.scale(0.02)
plt.axes(axs[0])
hist_data.plotHeatmap()
plt.text(0.95, 0.95, "data", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
plt.axes(axs[1])
hist_sim.plotHeatmap()
plt.text(0.95, 0.95, "simulation", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
for i in range(2):
    plt.axes(axs[i])
    plt.xlim(0.9, 1.1)
    plt.ylim(0, 10)
    plt.xlabel(r"$m_{K^+ K^-}$ (GeV/$c$)" )
    plt.ylabel(r"$\chi^2$/NDF")
file_pdf.savefig()
plt.close()

# phi mass vs minus t
print("Phi mass vs -t")
fig = plt.figure(figsize=(16, 6), dpi=300)
gs = fig.add_gridspec(1, 2)
axs = gs.subplots()
hist_data = file_data.get('PlotCut/phi_mass_minust_kin_PlotCut')
hist_sim = file_sim.get('PlotCut/phi_mass_minust_kin_PlotCut')
hist_sim.scale(0.02)
plt.axes(axs[0])
hist_data.plotHeatmap()
plt.text(0.95, 0.95, "data", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
plt.axes(axs[1])
hist_sim.plotHeatmap()
plt.text(0.95, 0.95, "simulation", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
for i in range(2):
    plt.axes(axs[i])
    plt.xlim(0.9, 1.1)
    plt.ylim(0, 2)
    plt.xlabel(r"$m_{K^+ K^-}$ (GeV/$c$)" )
    plt.ylabel(r"$-t (\mathrm{GeV}^2/c^4)$")
file_pdf.savefig()
plt.close()

# phi mass vs missing p minus
print("Phi mass vs Missing p minus")
fig = plt.figure(figsize=(16, 6), dpi=300)
gs = fig.add_gridspec(1, 2)
axs = gs.subplots()
hist_data = file_data.get('PlotCut/phi_mass_miss_pminus_meas_PlotCut')
hist_sim = file_sim.get('PlotCut/phi_mass_miss_pminus_meas_PlotCut')
hist_sim.scale(0.02)
plt.axes(axs[0])
hist_data.plotHeatmap()
plt.text(0.95, 0.95, "data", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
plt.axes(axs[1])
hist_sim.plotHeatmap()
plt.text(0.95, 0.95, "simulation", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
for i in range(2):
    plt.axes(axs[i])
    plt.xlim(0.9, 1.1)
    plt.ylim(-0.1, 0.1)
    plt.xlabel(r"$m_{K^+ K^-}$ (GeV/$c$)" )
    plt.ylabel(r"$p_{miss}^-$ (GeV/c)")
file_pdf.savefig()
plt.close()

# phi meson kinematics
print("Phi kinematics")
fig = plt.figure(figsize=(16, 6), dpi=300)
gs = fig.add_gridspec(1, 2)
axs = gs.subplots()
hist_data = file_data.get('PlotCut/phi_kinematics_kin_PlotCut')
hist_sim = file_sim.get('PlotCut/phi_kinematics_kin_PlotCut')
hist_sim.scale(0.02)
plt.axes(axs[0])
hist_data.plotHeatmap()
plt.text(0.95, 0.95, "data", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
plt.axes(axs[1])
hist_sim.plotHeatmap()
plt.text(0.95, 0.95, "simulation", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
for i in range(2):
    plt.axes(axs[i])
    plt.xlim(0, 10)
    plt.ylim(0, 90)
    plt.yticks(np.arange(0, 91, 10))
    plt.xlabel(r"$p_{\phi}$ (GeV/c)")
    plt.ylabel(r"$\theta_{\phi}$ (deg)")
file_pdf.savefig()
plt.close()

###################################################################### MISSING P4 #####################################################################################

# Missing energy
print("Missing energy")
fig = plt.figure(figsize=(8, 6), dpi=300)
hist_data = file_data.get('PlotCut/miss_energy_meas_PlotCut')
hist_sim = file_sim.get('PlotCut/miss_energy_meas_PlotCut')
hist_sim.scale(0.018)
hist_data.plotPoints(label="Data", marker='o', markersize=3, linestyle='None', color='black')
hist_sim.plotPoints(label="Sim", marker='o', markersize=3, linestyle='-', color='blue')
plt.bar(hist_data.x, hist_data.y, width=0.02, alpha=0.5, label='Data', color='green')
plt.xlim(-2, 2)
plt.xlabel(r"$E_{miss}$ (GeV)")
plt.ylabel("Counts")
plt.legend()
file_pdf.savefig()
plt.close()

# Missing mass squared
print("Missing mass squared")
fig = plt.figure(figsize=(8, 6), dpi=300)
hist_data = file_data.get('PlotCut/miss_masssquared_meas_PlotCut')
hist_sim = file_sim.get('PlotCut/miss_masssquared_meas_PlotCut')
hist_sim.scale(0.017)
hist_data.plotPoints(label="Data", marker='o', markersize=3, linestyle='-', color='black')
hist_sim.plotPoints(label="Sim", marker='o', markersize=3, linestyle='-', color='blue')
# plt.bar(hist_data.x, hist_data.y, width=0.02, alpha=0.5, label='Data', color='green')
plt.xlim(-0.1, 0.1)
plt.xlabel(r"$m^2_{miss} (GeV^2/c^4)$")
plt.ylabel("Counts")
plt.legend()
file_pdf.savefig()
plt.close()

# Missing p minus
print("Missing p minus")
fig = plt.figure(figsize=(8, 6), dpi=300)
hist_data = file_data.get('PlotCut/miss_pminus_meas_PlotCut')
hist_sim = file_sim.get('PlotCut/miss_pminus_meas_PlotCut')
hist_sim.scale(0.017)
hist_data.plotPoints(label="Data", marker='o', markersize=3, linestyle='-', color='black')
hist_sim.plotPoints(label="Sim", marker='o', markersize=3, linestyle='-', color='blue')
# plt.bar(hist_data.x, hist_data.y, width=0.02, alpha=0.5, label='Data', color='green')
plt.xlim(-0.1, 0.1)
plt.xlabel(r"$p_{miss}^-$ (GeV/c)")
plt.ylabel("Counts")
plt.legend()
file_pdf.savefig()
plt.close()

# Missing momentum
print("Missing momentum")
fig = plt.figure(figsize=(8, 6), dpi=300)
hist_data = file_data.get('PlotCut/miss_momentum_meas_PlotCut')
hist_sim = file_sim.get('PlotCut/miss_momentum_meas_PlotCut')
hist_sim.scale(0.017)
hist_data.plotPoints(label="Data", marker='o', markersize=3, linestyle='-', color='black')
hist_sim.plotPoints(label="Sim", marker='o', markersize=3, linestyle='-', color='blue')
# plt.bar(hist_data.x, hist_data.y, width=0.02, alpha=0.5, label='Data', color='green')
plt.xlim(0, 2.0)
plt.xlabel(r"$p_{miss} (GeV/c)$")
plt.ylabel("Counts")
plt.legend()
file_pdf.savefig()
plt.close()

# Missing momentum vs missing energy
print("Missing momentum vs Missing energy")
fig = plt.figure(figsize=(16, 6), dpi=300)
gs = fig.add_gridspec(1, 2)
axs = gs.subplots()
hist_data = file_data.get('PlotCut/miss_momentum_energy_meas_PlotCut')
hist_sim = file_sim.get('PlotCut/miss_momentum_energy_meas_PlotCut')
hist_sim.scale(0.02)
plt.axes(axs[0])
hist_data.plotHeatmap()
plt.text(0.95, 0.95, "data", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
plt.axes(axs[1])
hist_sim.plotHeatmap()
plt.text(0.95, 0.95, "simulation", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
for i in range(2):
    plt.axes(axs[i])
    plt.ylim(-2, 2)
    plt.xlim(0, 2)
    plt.ylabel(r"$E_{miss}$ (GeV)")
    plt.xlabel(r"$p_{miss} (GeV/c)$")
file_pdf.savefig()
plt.close()

# Missing energy vs phi mass
print("Missing energy vs Phi mass")
fig = plt.figure(figsize=(16, 6), dpi=300)
gs = fig.add_gridspec(1, 2)
axs = gs.subplots()
hist_data = file_data.get('PlotCut/miss_energy_phi_mass_meas_PlotCut')
hist_sim = file_sim.get('PlotCut/miss_energy_phi_mass_meas_PlotCut')
hist_sim.scale(0.02)
plt.axes(axs[0])
hist_data.plotHeatmap()
plt.text(0.95, 0.05, "data", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='bottom')
plt.axes(axs[1])
hist_sim.plotHeatmap()
plt.text(0.95, 0.05, "simulation", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='bottom')
for i in range(2):
    plt.axes(axs[i])
    plt.xlim(-2, 2)
    plt.ylim(0.9, 1.1)
    plt.xlabel(r"$E_{miss}$ (GeV)")
    plt.ylabel(r"$m_{K^+ K^-}$ (GeV/$c$)" )
file_pdf.savefig()
plt.close()

###################################################################### BACKGROUND #####################################################################################

# Number of unused tracks
print("Number of unused tracks")
fig = plt.figure(figsize=(8, 6), dpi=300)
hist_data = file_data.get('PlotCut/num_unused_tracks_meas_PlotCut')
hist_sim = file_sim.get('PlotCut/num_unused_tracks_meas_PlotCut')
hist_sim.scale(0.017)
hist_data.plotPoints(label="Data", marker='o', markersize=3, linestyle='None', color='black')
hist_sim.plotPoints(label="Sim", marker='o', markersize=3, linestyle='None', color='blue')
plt.bar(hist_data.x, hist_data.y, width=1, alpha=0.5, label='Data', color='green')
plt.xlim(0, 5)
plt.xlabel("Number of Unused Tracks")
plt.ylabel("Counts")
plt.legend()
file_pdf.savefig()
plt.close()

# Number of unused showers
print("Number of unused showers")
fig = plt.figure(figsize=(8, 6), dpi=300)
hist_data = file_data.get('PlotCut/num_unused_showers_meas_PlotCut')
hist_sim = file_sim.get('PlotCut/num_unused_showers_meas_PlotCut')
hist_sim.scale(0.017)
hist_data.plotPoints(label="Data", marker='o', markersize=3, linestyle='None', color='black')
hist_sim.plotPoints(label="Sim", marker='o', markersize=3, linestyle='None', color='blue')
plt.bar(hist_data.x, hist_data.y, width=1, alpha=0.5, label='Data', color='green')
plt.xlim(0, 10)
plt.xlabel("Number of Unused Showers")
plt.ylabel("Counts")
plt.legend()
file_pdf.savefig()
plt.close()

# Beam accidental weight
print("Beam accidental weight")
fig = plt.figure(figsize=(8, 6), dpi=300)
hist_data = file_data.get('PlotCut/beam_accid_weight_PlotCut')
hist_sim = file_sim.get('PlotCut/beam_accid_weight_PlotCut')
hist_sim.scale(0.006)
hist_data.plotPoints(label="Data", marker='o', markersize=3, linestyle='None', color='black')
hist_sim.plotPoints(label="Sim", marker='o', markersize=3, linestyle='None', color='blue')
plt.bar(hist_data.x, hist_data.y, width=0.1, alpha=0.5, label='Data', color='green')
plt.xlim(-0.5, 1.5)
plt.xlabel("Beam Accidental Weight")
plt.ylabel("Counts")
plt.legend()
file_pdf.savefig()
plt.close()

# Combo accidental weight
print("Combo accidental weight")
fig = plt.figure(figsize=(8, 6), dpi=300)
hist_data = file_data.get('PlotCut/combo_accid_weight_PlotCut')
hist_sim = file_sim.get('PlotCut/combo_accid_weight_PlotCut')
hist_sim.scale(0.006)
hist_data.plotPoints(label="Data", marker='o', markersize=3, linestyle='None', color='black')
hist_sim.plotPoints(label="Sim", marker='o', markersize=3, linestyle='None', color='blue')
plt.bar(hist_data.x, hist_data.y, width=1, alpha=0.5, label='Data', color='green')
plt.xlim(-0.5, 1.5)
plt.xlabel("Combo Accidental Weight")
plt.ylabel("Counts")
plt.legend()
file_pdf.savefig()
plt.close()

# Vertex z
print("Vertex z")
fig = plt.figure(figsize=(8, 6), dpi=300)
hist_data = file_data.get('PlotCut/vertex_z_kin_PlotCut')
hist_sim = file_sim.get('PlotCut/vertex_z_kin_PlotCut')
hist_sim.scale(0.0175)
hist_data.plotPoints(label="Data", marker='o', markersize=3, linestyle='None', color='black')
hist_sim.plotPoints(label="Sim", marker='o', markersize=3, linestyle='None', color='blue')
plt.xlim(40, 90)
plt.xlabel(r"Vertex $z$ (cm)")
plt.ylabel("Counts")
plt.legend()
file_pdf.savefig()
plt.close()

# Vertex x-y
print("Vertex x-y")
fig = plt.figure(figsize=(16, 6), dpi=300)
gs = fig.add_gridspec(1, 2)
axs = gs.subplots()
hist_data = file_data.get('PlotCut/vertex_x_y_kin_PlotCut')
hist_sim = file_sim.get('PlotCut/vertex_x_y_kin_PlotCut')
hist_sim.scale(0.02)
plt.axes(axs[0])
hist_data.plotHeatmap()
plt.text(0.95, 0.95, "data", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
plt.axes(axs[1])
hist_sim.plotHeatmap()
plt.text(0.95, 0.95, "simulation", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
for i in range(2):
    plt.axes(axs[i])
    plt.xlim(-1, 1)
    plt.ylim(-1, 1)
    plt.xlabel(r"Vertex $x$ (cm)")
    plt.ylabel(r"Vertex $y$ (cm)")
file_pdf.savefig()
plt.close()

# rho mass
print("Rho mass")
fig = plt.figure(figsize=(8, 6), dpi=300)
hist_data = file_data.get('PlotCut/rho_mass_kin_PlotCut')
hist_sim = file_sim.get('PlotCut/rho_mass_kin_PlotCut')
hist_sim.scale(0.024)
hist_data.plotPoints(label="Data", marker='o', markersize=3, linestyle='None', color='black')
hist_sim.plotPoints(label="Sim", marker='o', markersize=3, linestyle='None', color='blue')
plt.xlim(0.0, 1.0)
plt.xlabel(r"$m_{\pi^+ \pi^-}$ (GeV/$c$)" )
plt.ylabel("Counts")
plt.legend()
file_pdf.savefig()
plt.close()

# rho missing p minus
print("Rho missing p minus")
fig = plt.figure(figsize=(8, 6), dpi=300)
hist_data = file_data.get('PlotCut/rho_miss_pminus_meas_PlotCut')
hist_sim = file_sim.get('PlotCut/rho_miss_pminus_meas_PlotCut')
hist_sim.scale(0.0175)
hist_data.plotPoints(label="Data", marker='o', markersize=3, linestyle='None', color='black')
hist_sim.plotPoints(label="Sim", marker='o', markersize=3, linestyle='None', color='blue')
plt.xlim(-0.1, 0.1)
plt.xlabel(r"$p_{miss, \pi^+ \pi^-}^-$ (GeV/c)")
plt.ylabel("Counts")
plt.legend()
file_pdf.savefig()
plt.close()

# KinFit FOM
print("KinFit FOM")
fig = plt.figure(figsize=(8, 6), dpi=300)
hist_data = file_data.get('PlotCut/kinfit_fom_kin_PlotCut')
hist_sim = file_sim.get('PlotCut/kinfit_fom_kin_PlotCut')
hist_sim.scale(0.017)
hist_data.plotPoints(label="Data", marker='o', markersize=3, linestyle='None', color='black')
hist_sim.plotPoints(label="Sim", marker='o', markersize=3, linestyle='None', color='blue')
plt.xlim(-5, 0)
plt.yscale('log')
plt.xlabel("KinFit FOM")
plt.ylabel("Counts")
plt.legend()
file_pdf.savefig()
plt.close()

# KinFit Chi2
print("KinFit Chi2")
fig = plt.figure(figsize=(8, 6), dpi=300)
hist_data = file_data.get('PlotCut/chisq_per_ndf_kin_PlotCut')
hist_sim = file_sim.get('PlotCut/chisq_per_ndf_kin_PlotCut')
hist_sim.scale(0.017)
hist_data.plotPoints(label="Data", marker='o', markersize=3, linestyle='None', color='black')
hist_sim.plotPoints(label="Sim", marker='o', markersize=3, linestyle='None', color='blue')
plt.xlim(0, 10)
plt.xlabel(r"$\chi^2$/NDF")
plt.ylabel("Counts")
plt.legend()
file_pdf.savefig()
plt.close()

###################################################################### KINEMATICS #####################################################################################

# minus t
print("-t")
fig = plt.figure(figsize=(8, 6), dpi=300)
hist_data = file_data.get('PlotCut/minust_kin_PlotCut')
hist_sim = file_sim.get('PlotCut/minust_kin_PlotCut')
hist_sim.scale(0.018)
hist_data.plotPoints(label="Data", marker='o', markersize=3, linestyle='None', color='black')
hist_sim.plotPoints(label="Sim", marker='o', markersize=3, linestyle='None', color='blue')
plt.xlim(0, 2)
plt.xlabel(r"$-t (GeV^2/c^4)$")
plt.ylabel("Counts")
plt.legend()
file_pdf.savefig()
plt.close()

# minus t vs deuteron momentum
print("-t vs Deuteron Momentum")
fig = plt.figure(figsize=(16, 6), dpi=300)
gs = fig.add_gridspec(1, 2)
axs = gs.subplots()
hist_data = file_data.get('PlotCut/minust_kin_d_momentum_meas_PlotCut')
hist_sim = file_sim.get('PlotCut/minust_kin_d_momentum_meas_PlotCut')
hist_sim.scale(0.02)
plt.axes(axs[0])
hist_data.plotHeatmap()
plt.text(0.95, 0.95, "data", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
plt.axes(axs[1])
hist_sim.plotHeatmap()
plt.text(0.95, 0.95, "simulation", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
for i in range(2):
    plt.axes(axs[i])
    plt.xlim(0, 2)
    plt.ylim(0, 2)
    plt.xlabel(r"$p_d$ (GeV/c)")
    plt.ylabel(r"$-t (GeV^2/c^4)$")
file_pdf.savefig()
plt.close()

# minus t vs beam energy
print("-t vs Beam Energy")
fig = plt.figure(figsize=(16, 6), dpi=300)
gs = fig.add_gridspec(1, 2)
axs = gs.subplots()
hist_data = file_data.get('PlotCut/beam_energy_minust_kin_PlotCut')
hist_sim = file_sim.get('PlotCut/beam_energy_minust_kin_PlotCut')
hist_sim.scale(0.02)
plt.axes(axs[0])
hist_data.plotHeatmap()
plt.text(0.95, 0.95, "data", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
plt.axes(axs[1])
hist_sim.plotHeatmap()
plt.text(0.95, 0.95, "simulation", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
for i in range(2):
    plt.axes(axs[i])
    plt.xlim(5, 11)
    plt.ylim(0, 2)
    plt.xlabel(r"Beam $E$ (GeV)")
    plt.ylabel(r"$-t (GeV^2/c^4)$")
file_pdf.savefig()
plt.close()

# com scattering angle
print("COM Scattering Angle")
fig = plt.figure(figsize=(8, 6), dpi=300)
hist_data = file_data.get('PlotCut/scatter_theta_com_kin_PlotCut')
hist_sim = file_sim.get('PlotCut/scatter_theta_com_kin_PlotCut')
hist_sim.scale(0.017)
hist_data.plotPoints(label="Data", marker='o', markersize=3, linestyle='None', color='black')
hist_sim.plotPoints(label="Sim", marker='o', markersize=3, linestyle='None', color='blue')
plt.xlim(0, 180)
plt.xlabel(r"$\theta_{COM}$ (deg)")
plt.ylabel("Counts")
plt.legend()
file_pdf.savefig()
plt.close()

# minus t vs com scattering angle
print("-t vs COM Scattering Angle")
fig = plt.figure(figsize=(16, 6), dpi=300)
gs = fig.add_gridspec(1, 2)
axs = gs.subplots()
hist_data = file_data.get('PlotCut/minust_scatter_theta_com_kin_PlotCut')
hist_sim = file_sim.get('PlotCut/minust_scatter_theta_com_kin_PlotCut')
hist_sim.scale(0.02)
plt.axes(axs[0])
hist_data.plotHeatmap()
plt.text(0.95, 0.95, "data", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
plt.axes(axs[1])
hist_sim.plotHeatmap()
plt.text(0.95, 0.95, "simulation", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
for i in range(2):
    plt.axes(axs[i])
    plt.ylim(0, 40)
    plt.xlim(0, 2)
    plt.ylabel(r"$\theta_{COM}$ (deg)")
    plt.xlabel(r"$-t (GeV^2/c^4)$")
file_pdf.savefig()
plt.close()

# Coplanarity
print("Coplanarity")
fig = plt.figure(figsize=(8, 6), dpi=300)
hist_data = file_data.get('PlotCut/coplanarity_meas_PlotCut')
hist_sim = file_sim.get('PlotCut/coplanarity_meas_PlotCut')
hist_sim.scale(0.017)
hist_data.plotPoints(label="Data", marker='o', markersize=3, linestyle='None', color='black')
hist_sim.plotPoints(label="Sim", marker='o', markersize=3, linestyle='None', color='blue')
plt.xlim(170, 190)
plt.xlabel(r"Coplanarity (deg)")
plt.ylabel("Counts")
plt.legend()
file_pdf.savefig()
plt.close()

###################################################################### DECAY ANGLES #####################################################################################

# cos(vartheta)
print("cos(vartheta)")
fig = plt.figure(figsize=(8, 6), dpi=300)
hist_data = file_data.get('PlotCut/decay_costheta_helicity_kin_PlotCut')
hist_sim = file_sim.get('PlotCut/decay_costheta_helicity_kin_PlotCut')
hist_sim.scale(0.0175)
hist_data.plotPoints(label="Data", marker='o', markersize=3, linestyle='None', color='black')
hist_sim.plotPoints(label="Sim", marker='o', markersize=3, linestyle='None', color='blue')
plt.xlim(-1, 1)
plt.ylim(0, 2000)
plt.xlabel(r"$\cos\vartheta$")
plt.ylabel("Counts")
plt.legend()
file_pdf.savefig()
plt.close()

# Phi
print("Phi")
fig = plt.figure(figsize=(8, 6), dpi=300)
hist_data = file_data.get('PlotCut/polarization_phi_com_kin_PlotCut')
hist_sim = file_sim.get('PlotCut/polarization_phi_com_kin_PlotCut')
hist_sim.scale(0.0175)
hist_data.plotPoints(label="Data", marker='o', markersize=3, linestyle='None', color='black')
hist_sim.plotPoints(label="Sim", marker='o', markersize=3, linestyle='None', color='blue')
plt.xlim(-180, 180)
plt.ylim(0, 2000)
plt.xlabel(r"$\Phi$ (deg)")
plt.ylabel("Counts")
plt.legend()
file_pdf.savefig()
plt.close()

# varphi
print("varphi")
fig = plt.figure(figsize=(8, 6), dpi=300)
hist_data = file_data.get('PlotCut/decay_phi_helicity_kin_PlotCut')
hist_sim = file_sim.get('PlotCut/decay_phi_helicity_kin_PlotCut')
hist_sim.scale(0.0175)
hist_data.plotPoints(label="Data", marker='o', markersize=3, linestyle='None', color='black')
hist_sim.plotPoints(label="Sim", marker='o', markersize=3, linestyle='None', color='blue')
plt.xlim(-180, 180)
plt.ylim(0, 2000)
plt.xlabel(r"$\varphi$ (deg)")
plt.ylabel("Counts")
plt.legend()
file_pdf.savefig()
plt.close()

# psi
print("psi")
fig = plt.figure(figsize=(8, 6), dpi=300)
hist_data = file_data.get('PlotCut/psi_helicity_kin_PlotCut')
hist_sim = file_sim.get('PlotCut/psi_helicity_kin_PlotCut')
hist_sim.scale(0.0175)
hist_data.plotPoints(label="Data", marker='o', markersize=3, linestyle='None', color='black')
hist_sim.plotPoints(label="Sim", marker='o', markersize=3, linestyle='None', color='blue')
plt.xlim(-180, 180)
plt.ylim(0, 1000)
plt.xlabel(r"$\psi$ (deg)")
plt.ylabel("Counts")
plt.legend()
file_pdf.savefig()
plt.close()

##################################################################### TRUTH VARIABLES #####################################################################################

mass_photon     = 0
mass_deuteron   = 1.8756129
mass_phi        = 1.019445
Deg_To_Rad      = np.pi/180

energy_list = np.arange(6.0, 11.0, 1.0)
t_list = np.arange(-2.0, 0.0, 0.1)

phi_p = np.zeros((len(energy_list), len(t_list)))
phi_theta = np.zeros((len(energy_list), len(t_list)))
deuteron_p = np.zeros((len(energy_list), len(t_list)))
deuteron_theta = np.zeros((len(energy_list), len(t_list)))

for i, energy in enumerate(energy_list):
    for j, t in enumerate(t_list):
        P4_gamma = root.TLorentzVector(0, 0, energy, energy)
        P4_target = root.TLorentzVector(0, 0, 0, mass_deuteron)
        s = (P4_gamma + P4_target).Mag2()

        pi_cm = np.sqrt(((s-mass_phi**2-mass_photon**2)**2-4*mass_phi**2*mass_photon**2)/(4*s))
        pf_cm = np.sqrt(((s-mass_phi**2-mass_deuteron**2)**2-4*mass_phi**2*mass_deuteron**2)/(4*s))
        edi_cm = np.sqrt(pi_cm**2+mass_deuteron**2)
        edf_cm = np.sqrt(pf_cm**2+mass_deuteron**2)
        theta = np.arccos((t - 2*mass_deuteron**2 + 2*edi_cm*edf_cm)/(2*pi_cm*pf_cm))

        P4_phi = root.TLorentzVector()
        P4_deuteron = root.TLorentzVector()
        P4_phi.SetXYZM(0, pf_cm*np.sin(theta), pf_cm*np.cos(theta), mass_phi)
        P4_deuteron.SetXYZM(0, -pf_cm*np.sin(theta), -pf_cm*np.cos(theta), mass_deuteron)

        boost_cm = (P4_gamma+P4_target).BoostVector()

        P4_phi.Boost(boost_cm)
        P4_deuteron.Boost(boost_cm)

        phi_p[i][j] = P4_phi.P()
        phi_theta[i][j] = P4_phi.Theta()/Deg_To_Rad
        deuteron_p[i][j] = P4_deuteron.P()
        deuteron_theta[i][j] = P4_deuteron.Theta()/Deg_To_Rad

# Beam energy truth
print("Beam energy truth")
fig = plt.figure(figsize=(8, 6), dpi=300)
hist_sim    = file_sim.get('PlotCut/beam_energy_truth_PlotCut')
hist_tagged = file_tagged.get('NoCut/beam_energy_truth_NoCut')
hist_gen    = file_gen.get('NoCut/beam_energy_truth_NoCut')
hist_sim.scale(110)
hist_sim.plotPoints(label="detected", marker='o', markersize=3, linestyle='None', color='blue')
hist_tagged.plotPoints(label="tagged", marker='o', markersize=3, linestyle='None', color='orange')
hist_gen.plotPoints(label="gen", marker='o', markersize=3, linestyle='None', color='green')
plt.xlim(5, 11)
plt.xlabel(r"Beam $E$ Truth (GeV)")
plt.ylabel("Counts")
plt.legend()
file_pdf.savefig()
plt.close()

# phi mass truth
print("Phi mass truth")
fig = plt.figure(figsize=(8, 6), dpi=300)
hist_sim = file_sim.get('PlotCut/phi_mass_truth_PlotCut')
hist_gen = file_gen.get('NoCut/phi_mass_truth_NoCut')
hist_tagged = file_tagged.get('NoCut/phi_mass_truth_NoCut')
hist_sim.scale(110)
hist_sim.plotPoints(label="detected", marker='o', markersize=3, linestyle='None', color='blue')
hist_tagged.plotPoints(label="tagged", marker='o', markersize=3, linestyle='None', color='orange')
hist_gen.plotPoints(label="gen", marker='o', markersize=3, linestyle='None', color='green')
plt.xlim(0.9, 1.1)
plt.xlabel(r"$m_{K^+ K^-}$ Truth $(GeV/c^2)$")
plt.ylabel("Counts")
plt.legend()
file_pdf.savefig()
plt.close()

# K+ kinematics truth
print("K+ kinematics truth")
fig = plt.figure(figsize=(24, 6), dpi=300)
gs = fig.add_gridspec(1, 3)
axs = gs.subplots()
hist_sim = file_sim.get('PlotCut/kp_kinematics_truth_PlotCut')
hist_tagged = file_tagged.get('NoCut/kp_kinematics_truth_NoCut')
hist_gen = file_gen.get('NoCut/kp_kinematics_truth_NoCut')
hist_sim.scale(110)
plt.axes(axs[0])
hist_sim.plotHeatmap()
plt.text(0.95, 0.95, "detected", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
plt.axes(axs[1])
hist_tagged.plotHeatmap()
plt.text(0.95, 0.95, "tagged", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
plt.axes(axs[2])
hist_gen.plotHeatmap()
plt.text(0.95, 0.95, "gen", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
for i in range(3):
    plt.axes(axs[i])
    plt.xlim(0, 10)
    plt.ylim(0, 20)
    plt.yticks(np.arange(0, 21, 2))
    plt.xlabel(r"$p_{K^+}$ truth (GeV/c)")
    plt.ylabel(r"$\theta_{K^+}$ truth (deg)")
file_pdf.savefig()
plt.close()

# K- kinematics truth
print("K- kinematics truth")
fig = plt.figure(figsize=(24, 6), dpi=300)
gs = fig.add_gridspec(1, 3)
axs = gs.subplots()
hist_sim = file_sim.get('PlotCut/km_kinematics_truth_PlotCut')
hist_gen = file_gen.get('NoCut/km_kinematics_truth_NoCut')
hist_tagged = file_tagged.get('NoCut/km_kinematics_truth_NoCut')
hist_sim.scale(110)
plt.axes(axs[0])
hist_sim.plotHeatmap()
plt.text(0.95, 0.95, "detected", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
plt.axes(axs[1])
hist_tagged.plotHeatmap()
plt.text(0.95, 0.95, "tagged", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
plt.axes(axs[2])
hist_gen.plotHeatmap()
plt.text(0.95, 0.95, "gen", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
for i in range(3):
    plt.axes(axs[i])
    plt.xlim(0, 10)
    plt.ylim(0, 20)
    plt.yticks(np.arange(0, 21, 2))
    plt.xlabel(r"$p_{K^-}$ truth (GeV/c)")
    plt.ylabel(r"$\theta_{K^-}$ truth (deg)")
file_pdf.savefig()
plt.close()

# d kinematics truth
print("d kinematics truth")
fig = plt.figure(figsize=(32, 6), dpi=300)
gs = fig.add_gridspec(1, 4)
axs = gs.subplots()
hist_sim = file_sim.get('PlotCut/d_kinematics_truth_PlotCut')
hist_gen = file_gen.get('NoCut/d_kinematics_truth_NoCut')
hist_tagged = file_tagged.get('NoCut/d_kinematics_truth_NoCut')
hist_sim.scale(110)
plt.axes(axs[0])
hist_sim.plotHeatmap()
plt.text(0.95, 0.95, "detected", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
plt.axes(axs[1])
hist_tagged.plotHeatmap()
plt.text(0.95, 0.95, "tagged", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
plt.axes(axs[2])
hist_gen.plotHeatmap()
plt.text(0.95, 0.95, "gen", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
plt.axes(axs[3])
for i in range(np.size(energy_list)):
    plt.plot(deuteron_p[i], deuteron_theta[i], linestyle='-', label=f"E={energy_list[i]}")
    plt.text(deuteron_p[i][-1], deuteron_theta[i][-1], f"{energy_list[i]:.1f}", fontsize=6, ha='right', va='top')
for i in range(np.size(t_list)):
    plt.plot(deuteron_p[:,i], deuteron_theta[:,i], linestyle='-')
    plt.text(deuteron_p[-1][i], deuteron_theta[-1][i], f"{-t_list[i]:.1f}", fontsize=6, ha='left', va='bottom')
plt.text(0.95, 0.95, "kinematics", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
for i in range(4):
    plt.axes(axs[i])
    plt.xlim(0, 2)
    plt.ylim(50, 90)
    plt.yticks(np.arange(50, 91, 10))
    plt.xlabel(r"$p_{d}$ truth (GeV/c)")
    plt.ylabel(r"$\theta_{d}$ truth(deg)")
file_pdf.savefig()
plt.close()

# phi meson kinematics truth
print("Phi kinematics truth")
fig = plt.figure(figsize=(32, 6), dpi=300)
gs = fig.add_gridspec(1, 4)
axs = gs.subplots()
hist_sim = file_sim.get('PlotCut/phi_kinematics_truth_PlotCut')
hist_gen = file_gen.get('NoCut/phi_kinematics_truth_NoCut')
hist_tagged = file_tagged.get('NoCut/phi_kinematics_truth_NoCut')
hist_sim.scale(110)
plt.axes(axs[0])
hist_sim.plotHeatmap()
plt.text(0.95, 0.95, "detected", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
plt.axes(axs[1])
hist_tagged.plotHeatmap()
plt.text(0.95, 0.95, "tagged", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
plt.axes(axs[2])
hist_gen.plotHeatmap()
plt.text(0.95, 0.95, "gen", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
plt.axes(axs[3])
for i in range(np.size(energy_list)):
    plt.plot(phi_p[i], phi_theta[i], linestyle='-', label=f"E={energy_list[i]}")
    plt.text(phi_p[i][-1], phi_theta[i][-1], f"{energy_list[i]:.1f}", fontsize=6, ha='right', va='top')
for i in range(np.size(t_list)):
    plt.plot(phi_p[:,i], phi_theta[:,i], linestyle='-')
    plt.text(phi_p[-1][i], phi_theta[-1][i], f"{-t_list[i]:.1f}", fontsize=6, ha='left', va='bottom')
plt.text(0.95, 0.95, "kinematics", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
for i in range(4):
    plt.axes(axs[i])
    plt.xlim(5, 11)
    plt.ylim(0, 20)
    plt.yticks(np.arange(0, 21, 2))
    plt.xlabel(r"$p_{\phi}$ truth (GeV/c)")
    plt.ylabel(r"$\theta_{\phi}$ truth (deg)")
file_pdf.savefig()
plt.close()

# phi meson and d theta truth
print("Phi and d theta truth")
fig = plt.figure(figsize=(32, 6), dpi=300)
gs = fig.add_gridspec(1, 4)
axs = gs.subplots()
hist_sim = file_sim.get('PlotCut/phi_d_theta_truth_PlotCut')
hist_gen = file_gen.get('NoCut/phi_d_theta_truth_NoCut')
hist_tagged = file_tagged.get('NoCut/phi_d_theta_truth_NoCut')
hist_sim.scale(110)
plt.axes(axs[0])
hist_sim.plotHeatmap()
plt.text(0.95, 0.95, "detected", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
plt.axes(axs[1])
hist_tagged.plotHeatmap()
plt.text(0.95, 0.95, "tagged", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
plt.axes(axs[2])
hist_gen.plotHeatmap()
plt.text(0.95, 0.95, "gen", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
plt.axes(axs[3])
for i in range(np.size(energy_list)):
    plt.plot(deuteron_theta[i], phi_theta[i], linestyle='-', label=f"E={energy_list[i]}")
    plt.text(deuteron_theta[i][-1], phi_theta[i][-1], f"{energy_list[i]:.1f}", fontsize=6, ha='right', va='top')
for i in range(np.size(t_list)):
    plt.plot(deuteron_theta[:,i], phi_theta[:,i], linestyle='-')
    plt.text(deuteron_theta[-1][i], phi_theta[-1][i], f"{-t_list[i]:.1f}", fontsize=6, ha='left', va='bottom')
plt.text(0.95, 0.95, "kinematics", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
for i in range(4):
    plt.axes(axs[i])
    plt.xlim(50, 90)
    plt.ylim(0, 20)
    plt.xlabel(r"$\theta_{d}$ truth (deg)")
    plt.ylabel(r"$\theta_{\phi}$ truth (deg)")
file_pdf.savefig()
plt.close()

# phi meson and d momentum truth
print("Phi and d momentum truth")
fig = plt.figure(figsize=(32, 6), dpi=300)
gs = fig.add_gridspec(1, 4)
axs = gs.subplots()
hist_sim = file_sim.get('PlotCut/phi_d_momentum_truth_PlotCut')
hist_gen = file_gen.get('NoCut/phi_d_momentum_truth_NoCut')
hist_tagged = file_tagged.get('NoCut/phi_d_momentum_truth_NoCut')
hist_sim.scale(110)
plt.axes(axs[0])
hist_sim.plotHeatmap()
plt.text(0.95, 0.95, "detected", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
plt.axes(axs[1])
hist_tagged.plotHeatmap()
plt.text(0.95, 0.95, "tagged", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
plt.axes(axs[2])
hist_gen.plotHeatmap()
plt.text(0.95, 0.95, "gen", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
plt.axes(axs[3])
for i in range(np.size(energy_list)):
    plt.plot(deuteron_p[i], phi_p[i], linestyle='-', label=f"E={energy_list[i]}")
    plt.text(deuteron_p[i][-1], phi_p[i][-1], f"{energy_list[i]:.1f}", fontsize=6, ha='right', va='top')
for i in range(np.size(t_list)):
    plt.plot(deuteron_p[:,i], phi_p[:,i], linestyle='-')
    plt.text(deuteron_p[-1][i], phi_p[-1][i], f"{-t_list[i]:.1f}", fontsize=6, ha='left', va='bottom')
plt.text(0.95, 0.95, "kinematics", transform=plt.gca().transAxes, fontsize=16, fontstyle='italic', ha='right', va='top')
for i in range(4):
    plt.axes(axs[i])
    plt.xlim(0, 2)
    plt.ylim(5, 11)
    plt.xlabel(r"$p_{d}$ truth (GeV/c)")
    plt.ylabel(r"$p_{\phi}$ truth (GeV/c)")
file_pdf.savefig()
plt.close()

# minus t truth
print("-t truth")
fig = plt.figure(figsize=(8, 6), dpi=300)
hist_sim = file_sim.get('PlotCut/minust_truth_PlotCut')
hist_gen = file_gen.get('NoCut/minust_truth_NoCut')
hist_tagged = file_tagged.get('NoCut/minust_truth_NoCut')
hist_sim.scale(4)
hist_sim.plotPoints(label="detected", marker='o', markersize=3, linestyle='None', color='blue')
hist_tagged.plotPoints(label="tagged", marker='o', markersize=3, linestyle='None', color='orange')
hist_gen.plotPoints(label="gen", marker='o', markersize=3, linestyle='None', color='green')
plt.xlim(0, 2)
plt.xlabel(r"$-t$ truth $(\rm{GeV}^2/c^4)$")
plt.ylabel("Counts")
plt.yscale('log')
plt.legend()
file_pdf.savefig()
plt.close()

# com scattering angle truth
print("COM scattering angle truth")
fig = plt.figure(figsize=(8, 6), dpi=300)
hist_sim = file_sim.get('PlotCut/scatter_theta_com_truth_PlotCut')
hist_gen = file_gen.get('NoCut/scatter_theta_com_truth_NoCut')
hist_tagged = file_tagged.get('NoCut/scatter_theta_com_truth_NoCut')
hist_sim.scale(4)
hist_sim.plotPoints(label="detected", marker='o', markersize=3, linestyle='None', color='blue')
hist_tagged.plotPoints(label="tagged", marker='o', markersize=3, linestyle='None', color='orange')
hist_gen.plotPoints(label="gen", marker='o', markersize=3, linestyle='None', color='green')
plt.xlim(0, 180)
plt.xlabel(r"$\theta_{COM}$ Truth (deg)")
plt.ylabel("Counts")
plt.yscale('log')
plt.legend()
file_pdf.savefig()
plt.close()

# decay cos(vartheta) truth
print("Decay cos(vartheta) truth")
fig = plt.figure(figsize=(8, 6), dpi=300)
hist_sim = file_sim.get('PlotCut/decay_costheta_helicity_truth_PlotCut')
hist_gen = file_gen.get('NoCut/decay_costheta_helicity_truth_NoCut')
hist_tagged = file_tagged.get('NoCut/decay_costheta_helicity_truth_NoCut')
hist_sim.scale(110)
hist_sim.plotPoints(label="detected", marker='o', markersize=3, linestyle='None', color='blue')
hist_tagged.plotPoints(label="tagged", marker='o', markersize=3, linestyle='None', color='orange')
hist_gen.plotPoints(label="gen", marker='o', markersize=3, linestyle='None', color='green')
plt.xlim(-1, 1)
plt.xlabel(r"Decay $\cos\vartheta$ Truth")
plt.ylabel("Counts")
plt.legend()
file_pdf.savefig()
plt.close()

# decay phi truth
print("Decay phi truth")
fig = plt.figure(figsize=(8, 6), dpi=300)
hist_sim = file_sim.get('PlotCut/decay_phi_helicity_truth_PlotCut')
hist_gen = file_gen.get('NoCut/decay_phi_helicity_truth_NoCut')
hist_tagged = file_tagged.get('NoCut/decay_phi_helicity_truth_NoCut')
hist_sim.scale(110)
hist_sim.plotPoints(label="detected", marker='o', markersize=3, linestyle='None', color='blue')
hist_tagged.plotPoints(label="tagged", marker='o', markersize=3, linestyle='None', color='orange')
hist_gen.plotPoints(label="gen", marker='o', markersize=3, linestyle='None', color='green')
plt.xlim(-180, 180)
plt.xlabel(r"Decay $\varphi$ Truth (deg)")
plt.ylabel("Counts")
plt.legend()
file_pdf.savefig()
plt.close()

# polarization phi truth
print("Polarization phi truth")
fig = plt.figure(figsize=(8, 6), dpi=300)
hist_sim = file_sim.get('PlotCut/polarization_phi_com_truth_PlotCut')
hist_gen = file_gen.get('NoCut/polarization_phi_com_truth_NoCut')
hist_tagged = file_tagged.get('NoCut/polarization_phi_com_truth_NoCut')
hist_sim.scale(110)
hist_sim.plotPoints(label="detected", marker='o', markersize=3, linestyle='None', color='blue')
hist_tagged.plotPoints(label="tagged", marker='o', markersize=3, linestyle='None', color='orange')
hist_gen.plotPoints(label="gen", marker='o', markersize=3, linestyle='None', color='green')
plt.xlim(-180, 180)
plt.xlabel(r"Polarization $\Phi$ Truth (deg)")
plt.ylabel("Counts")
plt.legend()
file_pdf.savefig()
plt.close()

# decay psi truth
print("Decay psi truth")
fig = plt.figure(figsize=(8, 6), dpi=300)
hist_sim = file_sim.get('PlotCut/psi_helicity_truth_PlotCut')
hist_gen = file_gen.get('NoCut/psi_helicity_truth_NoCut')
hist_tagged = file_tagged.get('NoCut/psi_helicity_truth_NoCut')
hist_sim.scale(110)
hist_sim.plotPoints(label="detected", marker='o', markersize=3, linestyle='None', color='blue')
hist_tagged.plotPoints(label="tagged", marker='o', markersize=3, linestyle='None', color='orange')
hist_gen.plotPoints(label="gen", marker='o', markersize=3, linestyle='None', color='green')
plt.xlim(-180, 180)
plt.xlabel(r"Decay $\psi$ Truth (deg)")
plt.ylabel("Counts")
plt.legend()
file_pdf.savefig()
plt.close()

###################################################################### BIN MIGRATIONS #####################################################################################

# beam energy bin migration
print("beam energy bin migration")
fig = plt.figure(figsize=(8, 6), dpi=300)
hist_sim = file_sim.get('PlotCut/beam_energy_kin_truth_PlotCut')
hist_sim.z[hist_sim.z<=0] = np.nan
hist_sim.z = np.log10(hist_sim.z)
hist_sim.plotHeatmap()
plt.ylabel(r"Beam $E$ detected")
plt.xlabel(r"Beam $E$ thrown")
plt.colorbar(label=r"$\log_{10}$(Counts)")
file_pdf.savefig()
plt.close()

# minus t bin migration
print("minus t bin migration")
fig = plt.figure(figsize=(8, 6), dpi=300)
hist_sim = file_sim.get('PlotCut/minust_kin_truth_PlotCut')
hist_sim.z[hist_sim.z<=0] = np.nan
hist_sim.z = np.log10(hist_sim.z)
hist_sim.plotHeatmap()
plt.ylabel(r"$-t$ reconstructed $(\mathrm{GeV}^2/c^4)$")
plt.xlabel(r"$-t$ thrown $(\mathrm{GeV}^2/c^4)$")
plt.colorbar(label=r"$\log_{10}$(Counts)")
file_pdf.savefig()
plt.close()

###################################################################### RESOLUTIONS #####################################################################################

def gaussian(x, a, b, c):
    return a*np.exp(-0.5*((x-b)/c)**2)

# minus t resolution
print("-t resolution")
fig = plt.figure(figsize=(8, 6), dpi=300)
hist_sim = file_sim.get('PlotCut/minust_diff_PlotCut')
for i in range(4, np.size(hist_sim.xedge)-1):
    this_ycenter = (hist_sim.yedge[:-1] + hist_sim.yedge[1:]) / 2
    this_average = np.average(this_ycenter, weights=hist_sim.z[:, i])
    this_std = np.sqrt(np.average((this_ycenter - this_average)**2, weights=hist_sim.z[:, i]))
    popt, pcov = curve_fit(gaussian, this_ycenter, hist_sim.z[:, i], p0=[hist_sim.z[:, i].max(),this_average,this_std])
    plt.errorbar(hist_sim.xedge[i]+(hist_sim.xedge[i+1]-hist_sim.xedge[i])/2, popt[1], yerr=popt[2], fmt='.', color='red')
hist_sim.z[hist_sim.z<=0] = np.nan
hist_sim.z = np.log10(hist_sim.z)
hist_sim.plotHeatmap()
plt.ylabel(r"$\Delta t (GeV^2/c^4)$")
plt.xlabel(r"$-t (GeV^2/c^4)$")
plt.ylim(-0.1, 0.1)
plt.colorbar(label=r"$\log_{10}$(Counts)")
file_pdf.savefig()
plt.close()

# costheta resolution
print("costheta resolution")
fig = plt.figure(figsize=(8, 6), dpi=300)
hist_sim = file_sim.get('PlotCut/decay_costheta_helicity_diff_PlotCut')
for i in range(4, np.size(hist_sim.xedge)-1):
    this_ycenter = (hist_sim.yedge[:-1] + hist_sim.yedge[1:]) / 2
    this_average = np.average(this_ycenter, weights=hist_sim.z[:, i])
    this_std = np.sqrt(np.average((this_ycenter - this_average)**2, weights=hist_sim.z[:, i]))
    popt, pcov = curve_fit(gaussian, this_ycenter, hist_sim.z[:, i], p0=[hist_sim.z[:, i].max(),this_average,this_std])
    plt.errorbar(hist_sim.xedge[i]+(hist_sim.xedge[i+1]-hist_sim.xedge[i])/2, popt[1], yerr=popt[2], fmt='.', color='red')
hist_sim.z[hist_sim.z<=0] = np.nan
hist_sim.z = np.log10(hist_sim.z)
hist_sim.plotHeatmap()
plt.ylabel(r"$\Delta \cos\vartheta$")
plt.xlabel(r"$-t (GeV^2/c^4)$")
plt.ylim(-0.5, 0.5)
file_pdf.savefig()
plt.close()

# decayphi resolution
print("decayphi resolution")
fig = plt.figure(figsize=(8, 6), dpi=300)
hist_sim = file_sim.get('PlotCut/decay_phi_helicity_diff_PlotCut')
for i in range(4, np.size(hist_sim.xedge)-1):
    this_ycenter = (hist_sim.yedge[:-1] + hist_sim.yedge[1:]) / 2
    this_average = np.average(this_ycenter, weights=hist_sim.z[:, i])
    this_std = np.sqrt(np.average((this_ycenter - this_average)**2, weights=hist_sim.z[:, i]))
    popt, pcov = curve_fit(gaussian, this_ycenter, hist_sim.z[:, i], p0=[hist_sim.z[:, i].max(),this_average,this_std])
    plt.errorbar(hist_sim.xedge[i]+(hist_sim.xedge[i+1]-hist_sim.xedge[i])/2, popt[1], yerr=popt[2], fmt='.', color='red')
hist_sim.z[hist_sim.z<=0] = np.nan
hist_sim.z = np.log10(hist_sim.z)
hist_sim.plotHeatmap()
plt.ylabel(r"$\Delta \varphi$ (deg)")
plt.xlabel(r"$-t (GeV^2/c^4)$")
plt.colorbar(label=r"$\log_{10}$(Counts)")
file_pdf.savefig()
plt.close()

# polphi resolution
print("polphi resolution")
fig = plt.figure(figsize=(8, 6), dpi=300)
hist_sim = file_sim.get('PlotCut/polarization_phi_com_diff_PlotCut')
for i in range(4, np.size(hist_sim.xedge)-1):
    this_ycenter = (hist_sim.yedge[:-1] + hist_sim.yedge[1:]) / 2
    this_average = np.average(this_ycenter, weights=hist_sim.z[:, i])
    this_std = np.sqrt(np.average((this_ycenter - this_average)**2, weights=hist_sim.z[:, i]))
    popt, pcov = curve_fit(gaussian, this_ycenter, hist_sim.z[:, i], p0=[hist_sim.z[:, i].max(),this_average,this_std])
    plt.errorbar(hist_sim.xedge[i]+(hist_sim.xedge[i+1]-hist_sim.xedge[i])/2, popt[1], yerr=popt[2], fmt='.', color='red')
hist_sim.z[hist_sim.z<=0] = np.nan
hist_sim.z = np.log10(hist_sim.z)
hist_sim.plotHeatmap()
plt.ylabel(r"$\Delta \Phi$ (deg)")
plt.xlabel(r"$-t (GeV^2/c^4)$")
plt.colorbar(label=r"$\log_{10}$(Counts)")
file_pdf.savefig()
plt.close()

# psi resolution
print("psi resolution")
fig = plt.figure(figsize=(8, 6), dpi=300)
hist_sim = file_sim.get('PlotCut/psi_helicity_diff_PlotCut')
for i in range(4, np.size(hist_sim.xedge)-1):
    this_ycenter = (hist_sim.yedge[:-1] + hist_sim.yedge[1:]) / 2
    this_average = np.average(this_ycenter, weights=hist_sim.z[:, i])
    this_std = np.sqrt(np.average((this_ycenter - this_average)**2, weights=hist_sim.z[:, i]))
    popt, pcov = curve_fit(gaussian, this_ycenter, hist_sim.z[:, i], p0=[hist_sim.z[:, i].max(),this_average,this_std])
    plt.errorbar(hist_sim.xedge[i]+(hist_sim.xedge[i+1]-hist_sim.xedge[i])/2, popt[1], yerr=popt[2], fmt='.', color='red')
hist_sim.z[hist_sim.z<=0] = np.nan
hist_sim.z = np.log10(hist_sim.z)
hist_sim.plotHeatmap()
plt.ylabel(r"$\Delta \psi$ (deg)")
plt.xlabel(r"$-t (GeV^2/c^4)$")
plt.colorbar(label=r"$\log_{10}$(Counts)")
file_pdf.savefig()
plt.close()

# phi mass resolution
print("Phi mass resolution")
fig = plt.figure(figsize=(8, 6), dpi=300)
hist_sim = file_sim.get('PlotCut/phi_mass_diff_PlotCut')
for i in range(4, np.size(hist_sim.xedge)-1):
    this_ycenter = (hist_sim.yedge[:-1] + hist_sim.yedge[1:]) / 2
    this_average = np.average(this_ycenter, weights=hist_sim.z[:, i])
    this_std = np.sqrt(np.average((this_ycenter - this_average)**2, weights=hist_sim.z[:, i]))
    popt, pcov = curve_fit(gaussian, this_ycenter, hist_sim.z[:, i], p0=[hist_sim.z[:, i].max(),this_average,this_std])
    plt.errorbar(hist_sim.xedge[i]+(hist_sim.xedge[i+1]-hist_sim.xedge[i])/2, popt[1], yerr=popt[2], fmt='.', color='red')
hist_sim.z[hist_sim.z<=0] = np.nan
hist_sim.z = np.log10(hist_sim.z)
hist_sim.plotHeatmap()
plt.ylabel(r"$\Delta$ Phi Mass (GeV/c^2)")
plt.xlabel(r"$-t (GeV^2/c^4)$")
plt.colorbar(label=r"$\log_{10}$(Counts)")
file_pdf.savefig()
plt.close()

###################################################################### END #####################################################################################

file_pdf.close()